# Generated by Django 3.0.3 on 2020-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='identifier',
            field=models.CharField(default='400467:9080732', max_length=256),
            preserve_default=False,
        ),
    ]
